Paginate = 4
baseURL = "/"
copyright = "All rights reserved - 2018"
description = "I'm a freelance iOS/Swift consultant."
languageCode = "en-us"
theme = "kube"
title = "Beat Rupp"
[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 2
[params]
author = "Beat Rupp"
email = "myemail@myaddress.xxx"
github = "beatrupp"
rsslink = "/index.xml"
twitter = "beatrupp"
